### ISSUE TITLE
[IDEA] inject `community.docker` into the requirements

### ISSUE THREAD

**Issue by JensHeinrich** [ansible-community/molecule-docker#147]
The requirement of `community.docker` is documented in the README.md, but installing it along side the role requirements seems to be the "easier" solution from a user standpoint

**Comment by zhan9san** [comment]
Hi @JensHeinrich 

The `community.docker` is installed when we run `molecule test` or `molecule dependency` automatically.

And users won't need to install it explicitly.

Do you encounter any issue?

**Comment by ssbarnea** [comment]
This is currently impossible and in fact the entire driver is in a very delicate spot, basically because community.docker -> docker-compose(py) and is in direct conflict with ansible-lint due to its capping of jsonschema version.

Basically docker driver became unusable with linter and docker has no visible plans to address this.

**Comment by JensHeinrich** [comment]
> Hi @JensHeinrich
> 
> The `community.docker` is installed when we run `molecule test` or `molecule dependency` automatically.
> 
> And users won't need to install it explicitly.
> 
> Do you encounter any issue?

If requirements are defined, the docker collection was not installed when I tried it out

**Comment by zhan9san** [comment]
@JensHeinrich 

If you are using Monolith Repo, the directory layout may be as below.

```shell
$ tree .
.
├── ansible.cfg
├── ansible_collections
│   └── community
└── roles
    └── stuff
        ├── README.md
        ├── defaults
        │   └── main.yml
        ├── files
        ├── handlers
        │   └── main.yml
        ├── meta
        │   └── main.yml
        ├── molecule
        │   └── default
        │       ├── converge.yml
        │       ├── molecule.yml
        │       └── verify.yml
        ├── tasks
        │   └── main.yml
        ├── templates
        ├── tests
        │   ├── inventory
        │   └── test.yml
        └── vars
            └── main.yml

14 directories, 12 files
```

From [monolith repo docs](https://molecule.readthedocs.io/en/latest/examples.html#monolith-repo), we run molecule command in roles directory instead of root directory.

But as you said, the `ansible.cfg` is in root folder, that's why `molecule` doesn't see it.

Besides, `molecule` will try to install requirements in an isolated cache dir, even you define your customized `ANSIBLE_ROLES_PATH`.

What if you set customized `ANSIBLE_ROLES_PATH`?
Without installing roles in your customized `ANSIBLE_ROLES_PATH`, `molecule` will search roles in it.


Here is my suggestion.

1. Define your requirements in a `requirements.yml` in role directory instead of `molecule.yml`. And when you run `molecule`, they will be installed in an isolated cache dir for each single role. It's for test or CI scenario.
2. You can still put `ansible.cfg` in root folder in which customized role path and collection path can be defined. Then you can install them by `ansible-galaxy` in root folder. It's for running playbook scenario.

Generally, test/CI runs on CI servers.

Does it make sense?

**Comment by ssbarnea** [comment]
Molecule is already able to dynamically install the required version of community.docker when needed, so we will not do anything about that. If you want to keep your test deps in order, do it manually with your own requirements file.
