### ISSUE TITLE
Molecule Windows Testing with WSL and Docker? 

### ISSUE THREAD

**Issue by james-m-tubbs** [ansible-community/molecule-docker#34]
Cross posted from: https://github.com/ansible-community/molecule/discussions/2995

I know there are some [existing strategies](https://github.com/ansible-community/molecule/issues/607) around testing molecule against windows targets, but I was thinking about other options (that don't include a hefty vagrant/virtualbox combo). AFAIK there are a few things we need to make this work:

* molecule can be [installed onto WSL](https://www.techdrabble.com/ansible/36-install-ansible-molecule-vagrant-on-windows-wsl) ✔️ 
* Use docker on the [host OS](https://nickjanetakis.com/blog/setting-up-docker-for-windows-and-wsl-to-work-flawlessly) ✔️ 
* molecule needs to connect using winrm. In theory this should work by:
  - [enabling winrm](https://superuser.com/questions/1580793/how-to-configure-winrm-on-windows-container-to-accept-connections-from-winrs-fro) on the host/container
  - Updating the molecule connection to [use winrm](https://github.com/ansible-community/molecule/issues/607#issuecomment-296164115)

Has anyone tried this and/or is there anything i'm missing here?

**Comment by jimbo8098** [comment]
I don't think that issue is related unless you are intending on starting a Windows container, running a WSL2 container within then testing against that WSL2 container. The current WSL2 meta doesn't really allow for creation in the way something like Virtualbox does because it's not really what it's intended for. 

If, on the other hand, you are just looking to start a Docker container to run on Windows and test against that, I see no reason to not use the molecule-vagrant driver to bootstrap such an environment if the default Docker driver doesn't work as you intend. 

Maybe I'm misunderstanding though, if so, please elaborate on your question and I'm sure someone will be able to assist you.

**Comment by ssbarnea** [comment]
Closing as wontfix. If anyone wants to do it, they will need to be able to drive that change, including adding GHA pipelines for testing it.
